import type { Metadata } from 'next';
import { Cormorant_Garamond, Inter } from 'next/font/google';
import './globals.css';
import { siteConfig } from '@/data/site';
import { ConsentBanner } from '@/components/ConsentBanner';
import { AttributionCapture } from '@/components/AttributionCapture';

const cormorant = Cormorant_Garamond({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  style: ['normal', 'italic'],
  variable: '--font-cormorant',
  display: 'swap',
});

const inter = Inter({
  subsets: ['latin'],
  weight: ['300', '400', '500'],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: `${siteConfig.name} | Find Vetted Will Writing Specialists in London`,
    template: `%s | ${siteConfig.name}`,
  },
  description: siteConfig.description,
  alternates: { canonical: siteConfig.url },
  robots: { index: true, follow: true },
  verification: {
    google: process.env.NEXT_PUBLIC_GSC_VERIFICATION ?? '0tiK29FqZZTfuLHttkRuIy6py1wNrbeADNmYqGWV2J4',
  },
  icons: {
    icon: [
      { url: '/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
      { url: '/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
      { url: '/favicon.ico' },
    ],
    apple: [{ url: '/apple-touch-icon.png', sizes: '180x180', type: 'image/png' }],
  },
  openGraph: {
    type: 'website', url: siteConfig.url, siteName: siteConfig.name,
    title: siteConfig.name, description: siteConfig.description, locale: 'en_GB',
    // og:image is supplied by the opengraph-image.tsx file convention
    // (per-route in app/, app/services/[serviceSlug]/, app/location/[city]/)
  },
  twitter: {
    card: 'summary_large_image', title: siteConfig.name, description: siteConfig.description,
    // twitter falls back to the og:image generated by the file convention
  },
};

const websiteSchema = {
  '@context': 'https://schema.org', '@type': 'WebSite',
  '@id': `${siteConfig.url}/#website`,
  name: siteConfig.name, url: siteConfig.url,
  potentialAction: {
    '@type': 'SearchAction',
    target: { '@type': 'EntryPoint', urlTemplate: `${siteConfig.url}/location/?q={search_term_string}` },
    'query-input': 'required name=search_term_string',
  },
};

const orgSchema = {
  '@context': 'https://schema.org', '@type': 'Organization',
  '@id': `${siteConfig.url}/#organization`,
  name: siteConfig.name, url: siteConfig.url,
  logo: `${siteConfig.url}/android-chrome-512x512.png`,
  description: 'Free matching service connecting London residents with vetted will writers and estate planning specialists. We are not a law firm — we introduce clients to qualified professionals.',
  areaServed: { '@type': 'AdministrativeArea', name: 'London', containedInPlace: { '@type': 'Country', name: 'United Kingdom' } },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const gaId = process.env.NEXT_PUBLIC_GA_ID ?? 'G-MKLSQNN51M';
  return (
    <html lang="en-GB" className={`${cormorant.variable} ${inter.variable}`}>
      <head>
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteSchema) }} />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(orgSchema) }} />
      </head>
      <body className="min-h-screen flex flex-col">
        {/* Skip to content — visually hidden until focused, first
            focusable element on every page (WCAG 2.4.1). */}
        <a href="#main-content" className="skip-link">Skip to main content</a>
        {/* First-touch attribution into sessionStorage. Fires before
            consent — captures only UTM params and document.referrer
            already exposed to the page, no analytics cookies. */}
        <AttributionCapture />
        {/* GA4 only loads after the visitor accepts the cookie banner
            (UK PECR requires prior consent for non-essential cookies). */}
        <ConsentBanner gaId={gaId} />
        {children}
      </body>
    </html>
  );
}
